name: CI
 
on:
  push:
    branches:
      - crawler
      - har-file
      - swagger
      - brokencrystals
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * THU"

jobs:
  start_and_wait_scan:
    runs-on: ubuntu-20.04
    name: A job to run a Bright Security scan
    steps:
      - uses: actions/checkout@v3.5.2
      - run: |
          sudo apt update
          sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo apt-get install nodejs node-gyp libssl1.0
          sudo apt-get install nodejs npm
          sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
      - name: Save environment variables
        run: |
          printf "NEXPLOIT_TOKEN=${{ secrets.NEXPLOIT_TOKEN }}" > .env
          cat .env
      - name: Docker-Compose
        run: |
          sudo docker-compose --env-file=.env up -d
          sudo docker-compose config
      - run: sleep 30s
      - run: sudo docker-compose logs
      - name: Start Bright Security Scan 🏁
        id: start
        run: |
          SCAN_ID=$(nexploit-cli scan:run                                                 \
            --test csrf dom_xss header_security secret_tokens open_buckets                 \
            --name "💎 BrokenCrystals for a '${GITHUB_REF##*/}' branch #${GITHUB_RUN_NUMBER}" \
            --crawler https://brokencrystals.com/api/config https://brokencrystals.com/  \
            --token ${{ secrets.NEXPLOIT_TOKEN }})
          echo "SCAN_ID=$SCAN_ID" >> $GITHUB_ENV
      - name: Get the output scan url 🔗
        run: |
          printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
      - name: Wait for issues ⏳
        run: |
          nexploit-cli scan:polling               \
            --interval 30s                        \
            --timeout 300m                         \
            --token ${{ secrets.NEXPLOIT_TOKEN }} \
            --breakpoint high_issue $SCAN_ID
      - name: Stop Scan 🛑
        continue-on-error: true
        if: ${{ always() }}
        run: nexploit-cli scan:stop --token ${{ secrets.NEXPLOIT_TOKEN }} $SCAN_ID
